services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  livekit:
    image: livekit/livekit-server:v1.9
    restart: unless-stopped
    ports:
      - "7880:7880"         # gRPC / HTTP APIs
      - "7881:7881"         # WebRTC over TCP
      - "3478:3478/udp"     # TURN
      - "50000-50010:50000-50010/udp"
    environment:
      LIVEKIT_REDIS_HOST: redis:6379
      LIVEKIT_KEYS: ${LIVEKIT_KEYS}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      LIVEKIT_INGRESS_USE_EXTERNAL_IP: "true"

  egress:
    build:
      context: .
      dockerfile: Dockerfile.egress
    image: livekit-egress:latest
    restart: unless-stopped
    depends_on: [livekit, redis]
    entrypoint: ["/bin/sh"]
    command: ["-c", "tail -f /dev/null"]
    environment:
      EGRESS_CONFIG_FILE: /egress.yaml
