services:
  redis:
    image: redis:latest
    restart: unless-stopped

  livekit:
    image: livekit/livekit-server:v1.9
    restart: unless-stopped
    ports:
      - "7880:7880"         # gRPC / HTTP APIs
      - "7881:7881"         # WebRTC over TCP
      - "3478:3478/udp"     # TURN
      - "50000-60000:50000-60000/udp"
    environment:
      LIVEKIT_REDIS_HOST: redis:6379
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      LIVEKIT_INGRESS_USE_EXTERNAL_IP: "true"

  egress:
    image: livekit/egress:v1.9
    restart: unless-stopped
    depends_on: [livekit, redis]
    environment:
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      LIVEKIT_WS_URL: ws://livekit:7880
      S3_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      S3_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_REGION:      ${AWS_DEFAULT_REGION}
      S3_BUCKET:      ${LIVEKIT_RECORDING_BUCKET}
    volumes:
      - ./egress.yaml:/egress.yaml:ro
    command: ["-config-file", "/egress.yaml"]
