global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 26.0.0

cache:
  enabled: true
  stack: kubernetes

extraEnvVars:
  - name: KC_CACHE_STACK
    value: "kubernetes"
  - name: KEYCLOAK_DATABASE_HOST
    value: "keycloak-postgresql"
  - name: KC_DB_URL_HOST
    value: "keycloak-postgresql"
  - name: KC_DB_URL_DATABASE
    value: "keycloak"
  - name: KC_DB_USERNAME
    value: "bn_keycloak"
  - name: KC_DB_PASSWORD
    value: "db-password"
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "YourSecurePassword123!"
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: "admin"
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: "YourSecurePassword123!"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"

auth:
  adminUser: admin
  adminPassword: "YourSecurePassword123!"
  databaseHost: "keycloak-postgresql"
  databaseName: "keycloak"
  databaseUser: "bn_keycloak"

# Use an external DB (PostgreSQL is recommended)
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: library/postgres
    tag: 15.8-alpine
  auth:
    database: keycloak
    username: bn_keycloak
    password: "db-password"
  tls:
    autoGenerated:
      enabled: false
  primary:
    extraEnvVars:
      - name: POSTGRES_DB
        value: "keycloak"
      - name: POSTGRES_USER
        value: "bn_keycloak"
      - name: POSTGRES_PASSWORD
        value: "db-password"
      - name: POSTGRES_PASSWORD_FILE
        value: ""
    extraVolumes:
      - name: postgres-run
        emptyDir: { }
    extraVolumeMounts:
      - name: postgres-run
        mountPath: /var/run/postgresql
  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: false
    runAsUser: 999
    runAsGroup: 999

# Keycloak-specific settings (Quarkus)
proxy: edge  # Set this if you are behind a LoadBalancer/Ingress
hostname: "auth.yourdomain.com"
httpRelativePath: "/"

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: auth.yourdomain.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: true
