apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oscar-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: oscar-web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
        podSelector:
          matchLabels:
            app.kubernetes.io/component: controller
      ports:
        - protocol: TCP
          port: {{ .Values.oscar.tomcat.http }}
        - protocol: TCP
          port: {{ .Values.oscar.tomcat.https }}
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: oscar-db
      ports:
        - protocol: TCP
          port: 3306
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oscar-db-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: oscar-db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: oscar-web
      ports:
        - protocol: TCP
          port: 3306
    - from:
      - podSelector:
          matchLabels:
            job-name: oscar-db-migrations
      ports:
        - protocol: TCP
          port: 3306
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
