apiVersion: apps/v1
kind: Deployment
metadata: { name: flask-api, namespace: {{ .Values.namespace }} }
spec:
  replicas: 2
  selector: { matchLabels: { app: flask-api } }
  template:
    metadata:
      labels:
        app: flask-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: api
          image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}"
          imagePullPolicy: "{{ .Values.flask.image.pullPolicy }}"
          env:
            {{ include "surrealdb.sharedEnv" . | indent 10 }}
          ports: [ { containerPort: 5000 } ]
---
apiVersion: v1
kind: Service
metadata: { name: flask-api, namespace: {{ .Values.namespace }} }
spec:
  selector: { app: flask-api }
  ports: [ { port: 80, targetPort: 5000 } ]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: webhooks-migration
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name:   webhooks-migration
          image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}"
          command: ["python", "lib/migrations/setup_webhooks.py"]
          env:
            {{ include "surrealdb.sharedEnv" . | indent 12 }}
