apiVersion: apps/v1
kind: Deployment
metadata: { name: mcp-server, namespace: {{ .Values.namespace }} }
spec:
  replicas: 2
  selector: { matchLabels: { app: mcp-server } }
  template:
    metadata:
      labels:
        app: mcp-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.mcp.port }}"
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: mcp-server
          image: "{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
          imagePullPolicy: "{{ .Values.mcp.image.pullPolicy }}"
          env:
            - name: PORT
              value: "{{ .Values.mcp.port }}"
          ports: [ { containerPort: {{ .Values.mcp.port }} } ]
---
apiVersion: v1
kind: Service
metadata: { name: mcp-server, namespace: {{ .Values.namespace }} }
spec:
  selector: { app: mcp-server }
  ports: [ { port: 80, targetPort: {{ .Values.mcp.port }} } ]
