version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: mariadb:10.6
    container_name: oscar-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecretroot
      MYSQL_DATABASE: oscar
      MYSQL_USER: oscar
      MYSQL_PASSWORD: oscarpw
      TZ: America/Toronto
    volumes:
      - oscar-db-data:/var/lib/mysql
    networks:
      - oscar-net

  oscar:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: db
        DB_PORT: 3306
        DB_NAME: oscar?useSSL=false&allowPublicKeyRetrieval=true
        DB_USER: oscar
        DB_PASSWORD: oscarpw
        TZ: America/Toronto
    container_name: oscar-web
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: oscar?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: oscar
      DB_PASSWORD: oscarpw
      TZ: America/Toronto
    # If you want HTTPS, you can map 8443:8443 (and configure Tomcat SSL).
    ports:
      - "8085:8080"
      - "8443:8443"
    volumes:
      # If you have a folder for the OscarDocument or logs, mount them here:
      # - ./oscar.properties:/usr/local/tomcat/conf/oscar.properties
      # - ./OscarDocument:/var/lib/OscarDocument
      - ./tomcat-logs:/usr/local/tomcat/logs
    networks:
      - oscar-net

volumes:
  oscar-db-data:

networks:
  oscar-net:
    driver: bridge
