name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: false # temporarily disabling the job
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: "test-encryption-key-for-ci-123456789"
      SENTRY_DSN: "test-sentry-dsn-for-ci-123456789"
    steps:
      - name: Bump release number
        run: |
          # Replace this with your actual release bumping logic
          echo "Bumping release number..."
          # Example: bump version in a VERSION file
          if [ -f VERSION ]; then
            oldver=$(cat VERSION)
            newver=$(echo $oldver | awk -F. -v OFS=. '{$NF++;print}')
            echo $newver > VERSION
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add VERSION
            git commit -m "Bump version to $newver [skip ci]"
            git push
          fi

      - name: K8s Deploy
        run: make k8s-deploy
