name: Deploy

#on:
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: "test-encryption-key-for-ci-123456789"
      SENTRY_DSN: "test-sentry-dsn-for-ci-123456789"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install MariaDB Connector/C
        run: sudo apt-get update && sudo apt-get install -y libmariadb-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Node.js dependencies
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Bump release number
        run: |
          # Replace this with your actual release bumping logic
          echo "Bumping release number..."
          # Example: bump version in a VERSION file
          if [ -f VERSION ]; then
            oldver=$(cat VERSION)
            newver=$(echo $oldver | awk -F. -v OFS=. '{$NF++;print}')
            echo $newver > VERSION
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add VERSION
            git commit -m "Bump version to $newver [skip ci]"
            git push
          fi

      - name: K8s Deploy
        run: make k8s-deploy
